#define CONFIG_CLOCK_FREQ 64000000
#define CONFIG_INLINE_STEPPER_HACK 1
#ifndef NO_EDGE_OPT
#define CONFIG_WANT_STEPPER_OPTIMIZED_BOTH_EDGE 1
#else
#define CONFIG_WANT_STEPPER_OPTIMIZED_BOTH_EDGE 0
#endif
#define CONFIG_MACH_AVR 0
